name: Build and Deploy to Cloud Run

on:
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: hometaskqueue
  RUN_REGION: us-west1
  SERVICE_NAME: hometaskqueue

jobs:
  setup-build-deploy:
    name: Just Build docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build vendor directory
      run: go mod vendor

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        project_id: hometaskqueue

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        docker build --tag=gcr.io/$PROJECT_ID/hometaskqueue:latest --file=./Dockerfile .